"""agregar columna placa

Revision ID: 1120d7d116b1
Revises: f0aaca03fa75
Create Date: 2026-06-11 17:43:54.165354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1120d7d116b1'
down_revision: Union[str, Sequence[str], None] = 'f0aaca03fa75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('placa', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_column('vehiculos', 'placa')
    # ### end Alembic commands ###
