"""agregar columnas color y kilometraje

Revision ID: 4942975705db
Revises: 1120d7d116b1
Create Date: 2026-06-11 17:44:10.422347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4942975705db'
down_revision: Union[str, Sequence[str], None] = '1120d7d116b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('vehiculos', sa.Column('kilometraje', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'kilometraje')
    op.drop_column('vehiculos', 'color')
    # ### end Alembic commands ###
