"""agregar campos: contraseña_hash, actualizado_en, numero_celular

Revision ID: d9f5878d6442
Revises: 9c3c94f76fe6
Create Date: 2026-06-08 19:31:07.830814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f5878d6442'
down_revision: Union[str, Sequence[str], None] = '9c3c94f76fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contraseña_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('actualizado_en', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('numero_celular', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_numero_celular'), 'users', ['numero_celular'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_numero_celular'), table_name='users')
    op.drop_column('users', 'numero_celular')
    op.drop_column('users', 'actualizado_en')
    op.drop_column('users', 'contraseña_hash')
    # ### end Alembic commands ###
